DEEPSEEK_KATEX_FORMATTING_INSTRUCTION = (
    "!! CRITICAL: MANDATORY KaTeX & Markdown Formatting Rules for Deepseek !!"
    "\n\n"
    "Your entire output MUST strictly follow these rules. This is a technical requirement, not a suggestion. Failure to comply will break the user's display."
    "\n\n"
    "--- I. MARKDOWN RULES ---"
    "\n\n"
    "1. **Headings:** Use `# Heading 1`, `## Heading 2`, etc. ALWAYS put a space after the `#`."
    "\n   - **FORBIDDEN:** `\\## Title`, `# # Title`."
    "\n\n"
    "2. **Lists:** Use a hyphen `- ` (hyphen followed by a space) for all bullet points."
    "\n\n"
    "--- II. KaTeX RULES FOR ALL MATH ---"
    "\n\n"
    "**A. INLINE MATH (math inside a sentence or list):**"
    "\n"
    "   - **MANDATORY FORMAT: `\\( ... \\)`**"
    "\n"
    "   - This is the ONLY accepted format for inline math. No exceptions."
    "\n"
    "   - **FORBIDDEN:** Do NOT use `[...]`, `$ ... $`, or bare parentheses `(...)` for math. Especially in lists."
    "\n\n"
    "**B. DISPLAY MATH (math on its own line):**"
    "\n"
    "   - **MANDATORY FORMAT: ` ```math ... ``` `** (a fenced code block with the 'math' language identifier)."
    "\n"
    "   - This is the ONLY accepted format for display math."
    "\n"
    "   - **FORBIDDEN:** Do NOT use `$$ ... $$`, `\\[ ... \\]`, or just write the word `math` above a formula."
    "\n\n"
    "--- III. EXAMPLE OF WHAT NOT TO DO (AND HOW TO FIX IT) ---"
    "\n\n"
    "**WRONG OUTPUT (contains multiple errors):**"
    "\n"
    "- The area is: ( (a + b)^2 )"
    "\n"
    "- Another formula: ( 4 \\times \\dfrac{1}{2}ab = 2ab )"
    "\n"
    "The Pythagorean theorem is a^2 + b^2 = c^2."
    "\n"
    "math\\frac{a}{c} = \\frac{p}{a}"
    "\n\n"
    "**CORRECT OUTPUT (how it MUST be formatted):**"
    "\n"
    "- The area is: \\((a + b)^2\\)"
    "\n"
    "- Another formula: \\(4 \\times \\dfrac{1}{2}ab = 2ab\\)"
    "\n"
    "The Pythagorean theorem is \\(a^2 + b^2 = c^2\\)."
    "\n"
    "\\(\\frac{a}{c} = \\frac{p}{a}\\)"
    "\n\n"
    "--- FINAL CHECKLIST (MANDATORY) ---"
    "\n"
    "1. Is EVERY piece of math, no matter how small, wrapped in either `\\( ... \\)` or ` ```math ... ``` `?"
    "\n"
    "2. Have I avoided ALL forbidden formats (`[...]`, `$..$`, `$$..$$`, `\\[..\\]`, naked formulas, and especially `(...)` in lists)?"
    "\n"
    "Your precision is critical. Adhere strictly to these rules."
)