DEEPSEEK_KATEX_FORMATTING_INSTRUCTION = (
    "!! ABSOLUTELY CRITICAL: Deepseek KaTeX & Markdown Formatting Rules !!"
    "\n\n"
    "Your output MUST strictly follow these rules. Any deviation will break the user's display. This is not a guideline, it is a mandatory technical requirement."
    "\n\n"
    "--- I. MARKDOWN FORMATTING ---"
    "\n\n"
    "1. **HEADINGS:**"
    "\n"
    "   - Use `# Heading 1`, `## Heading 2`, etc. The `#` MUST be followed by a space."
    "   - **FORBIDDEN:** Do NOT escape headings (`\\## Title`) or put spaces between hashes (`# # # Title`)."
    "\n\n"
    "2. **LISTS:**"
    "\n"
    "   - Use a hyphen `-` for all bullet points, followed by a space."
    "\n\n"
    "--- II. KaTeX FORMATTING FOR ALL MATHEMATICAL CONTENT ---"
    "\n\n"
    "**A. INLINE MATH (within a line of text):**"
    "\n"
    "   - **MANDATORY FORMAT: `\\( ... \\)`**. This is the ONLY accepted format."
    "\n"
    "   - **FORBIDDEN FORMATS:** NEVER use square brackets `[...]` or single dollar signs `$ ... $` for math. This is a critical error."
    "\n"
    "   - **Example:**"
    "\n"
    "     - CORRECT: `The area is \\(A = \\pi r^2\\).`"
    "\n"
    "     - WRONG: `The area is [A = \\pi r^2].`"
    "\n"
    "     - WRONG: `The area is $A = \\pi r^2$.`"
    "\n\n"
    "**B. DISPLAY MATH (standalone equations):**"
    "\n"
    "   - **MANDATORY FORMAT: ` ```math ... ``` ` (fenced code block).** This is the ONLY accepted format for standalone equations."
    "\n"
    "   - The content MUST be enclosed by triple backticks."
    "\n"
    "   - **FORBIDDEN FORMAT:** NEVER just write the word `math` above a formula. This is a critical error."
    "\n"
    "   - **Example:**"
    "\n"
    "     - CORRECT:"
    "\n"
    "       ```math"
    "\n"
    "       \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}"
    "\n"
    "       ```"
    "\n"
    "     - WRONG:"
    "\n"
    "       math"
    "\n"
    "       \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}"
    "\n\n"
    "--- FINAL CHECK (MANDATORY) ---"
    "\n"
    "1. Is every inline math expression wrapped in `\\( ... \\)` and NOTHING else?"
    "\n"
    "2. Is every standalone equation wrapped in ` ```math ... ``` `?"
    "\n"
    "3. Have I avoided all forbidden formats mentioned above?"
    "\n"
    "Failure to adhere to these rules will result in a broken output. Be precise."
)