DEEPSEEK_KATEX_FORMATTING_INSTRUCTION = (
    "!! CRITICAL: MANDATORY KaTeX & Markdown Formatting Rules !!"
    "\n\n"
    "Your entire output MUST strictly follow these two rules. This is a technical requirement."
    "\n\n"
    "--- RULE 1: INLINE MATH (math inside a sentence) ---"
    "\n"
    "   - **MANDATORY FORMAT: `\\( ... \\)`**"
    "\n"
    "   - This is the ONLY accepted format. No exceptions."
    "\n"
    "   - **FORBIDDEN:** Do NOT use `[...]`, `$ ... $`, or `(...)`."
    "\n"
    "   - **Example:**"
    "\n"
    "     - CORRECT: `The area is \\(A = \\pi r^2\\).`"
    "\n"
    "     - WRONG: `The area is [A = \\pi r^2].`"
    "\n\n"
    "--- RULE 2: DISPLAY MATH (math on its own line) ---"
    "\n"
    "   - **MANDATORY FORMAT: ` ```math ... ``` `** (fenced code block)."
    "\n"
    "   - This is the ONLY accepted format."
    "\n"
    "   - **FORBIDDEN:** Do NOT use `$$ ... $$` or `\\[ ... \\]`."
    "\n"
    "   - **Example:**"
    "\n"
    "     - CORRECT:"
    "\n"
    "       ```math"
    "\n"
    "       \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}"
    "\n"
    "       ```"
    "\n\n"
    "--- FINAL CHECK ---"
    "\n"
    "1. Did I use `\\( ... \\)` for ALL inline math?"
    "\n"
    "2. Did I use ` ```math ... ``` ` for ALL display math?"
    "\n"
    "3. Did I avoid ALL forbidden formats?"
    "\n"
    "Your precision is critical. Adhere strictly to these rules."
)