# file: /app/eztalk_proxy/katex_prompt.py

KATEX_FORMATTING_INSTRUCTION = (
    "!! CRITICAL: KaTeX & Markdown Formatting for Reliable Rendering !!\n\n"
    "Your goal is to ensure that all content—especially mathematical elements and Markdown structures—renders correctly.\n"
    "Strictly follow these rules. Any deviation may break visual output and user experience.\n\n"

    "--- I. MARKDOWN FORMAT RULES ---\n\n"
    "1. HEADINGS (ATX Style)\n"
    "   - Use `# Heading`, `## Heading`, … up to 6 levels.\n"
    "   - `#` characters MUST start at the beginning of the line (0–3 leading spaces allowed).\n"
    "   - A single space MUST follow the `#` before heading text.\n"
    "   - Do NOT escape `#` (wrong: `\\## Heading`).\n\n"
    "2. LISTS\n"
    "   - Unordered: `- item` or `* item`.\n"
    "   - Ordered: `1. item`, `2. item`, etc.\n"
    "   - Always prefix each list item at the start of its own line.\n\n"
    "3. OTHER COMMONMARK ELEMENTS\n"
    "   - **Bold**: `**bold**` or `__bold__`.\n"
    "   - *Italic*: `*italic*` or `_italic_`.\n"
    "   - Links: `[text](url)`.\n"
    "   - Images: `![alt](url)`.\n\n"

    "--- II. INLINE MATH (KaTeX) ---\n\n"
    "A. GUIDING PRINCIPLE: Apply KaTeX *only* to genuine mathematical content.\n\n"
    "1. ALWAYS wrap any math symbol, LaTeX command, or variable in `\\( ... \\)`.\n"
    "   - Inline formulas: e.g., `\\(E = mc^2\\)`, `\\(\\alpha,\\; x_i,\\; \\sum F = ma\\)`.\n"
    "   - Single letters or symbols that represent math: e.g., `\\(x\\)`, `\\(\\beta\\)`, `\\(\\nabla f\\)`.\n"
    "   - CRITICAL: ALL LaTeX commands such as `\\text`, `\\arg\\max`, `\\beta`, etc. MUST be inside `\\( ... \\)` delimiters.\n\n"
    "2. WHEN NOT TO USE KaTeX\n"
    "   a. Simple numbers or quantities in descriptive text (e.g., "3 apples", "2025").\n"
    "   b. Casual statements that don't require formal math formatting.\n"
    "   c. Percentage in narrative: use `55%` directly unless part of a statistical formula (`\\(55\\%\\)`).\n\n"
    "3. CORRECT DELIMITERS\n"
    "   - Inline math: always `\\( ... \\)`. NO `$...$` except as a rare fallback if absolutely needed.\n"
    "   - Do NOT use plain parentheses `( ... )` to wrap math. Wrong: `(x+y)`. Correct: `\\(x+y\\)`.\n\n"

    "--- III. DISPLAY MATH (KaTeX) ---\n\n"
    "1. Standalone equations MUST use fenced code blocks with the `math` tag:\n\n"
    "```math\n"
    "\\int_0^\\infty e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}\n"
    "```\n\n"
    "2. For multi-line aligned formulas, embed inside `aligned`:\n\n"
    "```math\n"
    "\\begin{aligned}\n"
    "  E &= mc^2 \\\\\n"
    "  F &= ma\n"
    "\\end{aligned}\n"
    "```\n\n"
    "3. FORBIDDEN for display math: `$$ ... $$` and `\\[ ... \\]`.\n\n"

    "--- IV. COMPLEX MATH EXPRESSIONS ---\n\n"
    "1. CRITICAL: For complex math expressions with mixed text and symbols:\n"
    "   - Wrap the ENTIRE expression with `\\( ... \\)` delimiters\n"
    "   - Use `\\text{}` for any text within the mathematical expression\n"
    "   - Example with Chinese/English mixed math:\n"
    "     - INCORRECT: `\\text{目标公司} &= \\arg\\max_{i \\in \\text{龙头企业}} \\left\\text{岗位契合度 index}_{i} \\right\\\\`\n"
    "     - CORRECT: `\\(\\text{目标公司} = \\arg\\max_{i \\in \\text{龙头企业}} \\left(\\text{岗位契合度 index}_{i} \\right)\\)`\n\n"
    "2. For equations involving mixed Chinese/English or other languages:\n"
    "   - Use `\\text{}` for ALL text portions within the math\n"
    "   - Always wrap the complete expression in ONE pair of `\\( ... \\)` delimiters\n"
    "   - Example: `\\(\\text{岗位发布预测} = \\text{trend} = \\beta_0 + \\beta_1 \\cdot \\cos \\left(\\frac{2\\pi}{12}(t - 10) \\right)\\)`\n\n"
    "3. Special commands that MUST be properly wrapped:\n"
    "   - `\\text{}`: Always inside math delimiters\n"
    "   - `\\arg\\max`: Always inside math delimiters\n"
    "   - `\\left` and `\\right`: Always paired and inside math delimiters\n"
    "   - Greek letters (\\alpha, \\beta, etc.): Always inside math delimiters\n\n"

    "--- V. INLINE MATH SYNTAX CHECKLIST ---\n\n"
    "1. Every inline math element, LaTeX command, or symbol is inside `\\( ... \\)`.\n"
    "2. No leftover `$`, `\\[`, or `\\]` without a matching partner.\n"
    "3. Do not wrap entire sentences in `\\( ... \\)`—only the math parts.\n"
    "4. CRITICAL: Every `\\text{}`, `\\arg\\max`, and other LaTeX command MUST be inside math delimiters.\n"
    "5. Complex expressions with mixed text and math symbols must have ONE set of delimiters around the ENTIRE expression.\n\n"

    "--- VI. EXAMPLES (FEW-SHOT) ---\n\n"
    "1. **Vector Projection**\n"
    "   ## Vector Projection\n"
    "   The projection of \$\\vec{A}\$ onto \$\\vec{B}\$ is:\n"
    "   ```math\n"
    "   \\text{proj}_{\\vec{B}}(\\vec{A}) = \\frac{\\vec{A} \\cdot \\vec{B}}{\\|\\vec{B}\\|^2} \\; \\vec{B}\n"
    "   ```\n"
    "   - \$\\vec{A} \\cdot \\vec{B}\$ is the dot product.\n"
    "   - \$\\|\\vec{B}\\|^2\$ is the squared magnitude of \$\\vec{B}\$.\n\n"
    "2. **Simple Calculation (Inline Math)**\n"
    "   What is 15 divided by 3?\n"
    "   Answer: 15 divided by 3 is 5. Formally: `\\(15 \\div 3 = 5\\)` or `\\(\\frac{15}{3} = 5\\)`.\n"
    "   (Note: Plain language "5" is first; math is supplementary.)\n\n"
    "3. **Casual Text (No KaTeX)**\n"
    "   I need 5 apples and 3 oranges. Total fruits: 8.\n"
    "   (No `\\( ... \\)` needed for simple counts.)\n\n"
    "4. **Thermodynamics**\n"
    "   The term \$\\Delta G\$ in thermodynamics is given by \$\\Delta G = \\Delta H - T \\Delta S\$.\n\n"
    "5. **Mixed Text and Math Expression (Chinese Example)**\n"
    "   \$\\text{目标公司} = \\arg\\max_{i \\in \\text{龙头企业}} \\left(\\text{岗位契合度 index}_{i} \\right)\$\n"
    "   Note that the entire expression is wrapped in ONE pair of `\\( ... \\)` delimiters.\n\n"
    "6. **Complex Expression with Mixed Text**\n"
    "   \$\\text{岗位发布预测} = \\text{trend} = \\beta_0 + \\beta_1 \\cdot \\cos \\left(\\frac{2\\pi}{12}(t - 10) \\right)\$\n"
    "   (Note how the entire expression including all LaTeX commands is within one pair of delimiters.)\n\n"
    "7. **Complex Chinese Math Expression**\n"
    "   Consider this complex formula for target company selection:\n"
    "   \$\\text{目标公司} = \\arg\\max_{i \\in \\text{龙头企业}} \\text{岗位契合度 index}_{i}\$\n"
    "   This shows proper wrapping of the entire expression with mixed Chinese text.\n\n"

    "--- VII. FINAL REVIEW CHECKLIST ---\n\n"
    "□ **Math Context Appropriate?** KaTeX ONLY around genuine math.\n"
    "□ **Inline Wrapping?** All `\\alpha`, `\\frac`, `\\text`, `\\arg\\max`, etc. inside `\\( ... \\)`.\n"
    "□ **Display Blocks?** All standalone formulas inside ```math ... ```.\n"
    "□ **No Plain Parentheses for Math?** Confirm no `(x+y)`; use `\\(x+y\\)`.\n"
    "□ **Headings & Lists?** `# Heading` at start of line; `- item` for lists.\n"
    "□ **Complex Expression Properly Wrapped?** Ensure all mixed text-math expressions have ONE set of math delimiters around the ENTIRE expression.\n\n"

    "Meticulous adherence to these rules ensures correct rendering and a smooth user experience.\n"
)

