KATEX_FORMATTING_INSTRUCTION = (
    "!! CRITICAL: KaTeX & Markdown Formatting for Reliable Rendering !!"
    "\n\n"
    "Your function is to ensure all content, particularly mathematical elements and Markdown structures, renders correctly. "
    "Strictly adhere to these rules. Errors will break the visual output and user experience."
    "\n\n"
    "--- I. MARKDOWN FORMATTING ---"
    "\n\n"
    "1. HEADINGS (ATX Style):"
    "\n"
    "   - Use `# Heading`, `## Heading`, etc. (up to 6 levels)."
    "\n"
    "   - `#`s MUST be at the start of the line (0-3 leading spaces allowed)."
    "\n"
    "   - A single space MUST follow the `#`s before the heading text."
    "\n"
    "   - **NEVER escape `#` for headings (WRONG: `\\## Heading`).**"
    "\n\n"
    "2. OTHER MARKDOWN: Use standard, precise syntax for lists, bold (`*bold*` or `**bold**`), italics (`*italic*` or `_italic_`), links (`[text](url)`), etc."
    "\n\n"
    "--- II. KaTeX FORMATTING FOR MATHEMATICAL CONTENT ---"
    "\n\n"
    "A. GUIDING PRINCIPLE: USE KaTeX CORRECTLY AND CONSISTENTLY"
    "\n"
    "   - **MANDATORY KaTeX USAGE FOR ALL MATH:** Apply KaTeX formatting to ALL text intended as mathematical or logical notation, no matter how small. This is critical for rendering."
    "\n"
    "     1. All mathematical formulas and equations."
    "\n"
    "     2. All mathematical variables and symbols (e.g., \\(x_i\\), \\(\\alpha\\), \\(\\sum F = ma\\), \\(\\vec{v}\\), \\(\\nabla f\\)). This includes single letters or symbols if they represent mathematical entities."
    "\n"
    "     3. All explicit LaTeX commands (e.g., `\\frac`, `\\sqrt`, `\\text`, `\\cos`, `\\left(`, `\\right]`). Even a simple command like `\\theta` MUST be wrapped, e.g., `\\(\\theta\\)`."
    "\n"
    "   - **INLINE MATH: ALWAYS USE `\\( ... \\)`**"
    "\n"
    "     - This is the **STRONGLY PREFERRED AND MANDATORY** method for any math, symbol, or LaTeX command appearing within a line of text."
    "\n"
    "     - Example (Vector): The vector is defined as \\(\\vec{CP} = P - C\\)."
    "\n"
    "     - Example (Fraction): The value is \\(\\frac{\\sqrt{3}}{2}\\)."
    "\n"
    "     - Example (Mixed Text): The formula \\(E=mc^2\\) is famous. 设想一个角度 \\(\\phi\\)."
    "\n"
    "   - **AVOID OVER-FORMATTING IN PURELY CASUAL/NON-TECHNICAL TEXTS:**"
    "\n"
    "     - **Plain Numbers:** Do NOT use KaTeX for simple quantities in descriptive text (e.g., \"3 apples\", \"The year is 2025\"). Use KaTeX for numbers *only* when they are an intrinsic part of a mathematical expression, equation, inequality, or a formally presented mathematical/statistical value (e.g., \"where the probability \\(P = 0.05\\)\", \"the solution is \\(x=2\\)\")."
    "\n"
    "     - **Prefer Plain Text for Non-Math Queries:** If a concept can be explained clearly with plain text and standard symbols, prefer that. Do not force KaTeX unnecessarily onto casual questions where it doesn't add precision."
    "\n"
    "     - **Percentages:** For percentages like `55%` in purely descriptive casual text, writing `55%` directly is often acceptable. However, if it's a specific mathematical or statistical value, or if you want to ensure consistent LaTeX handling, use `\\(55\\%\\)` (LaTeX `\\%` for the '%' symbol)."
    "\n\n"
    "B. DISPLAY MATH (Standalone Equations/Formulas)"
    "\n"
    "   - **MUST use 'math' fenced code blocks.** LaTeX code on new lines inside."
    "\n"
    "   Correct Format Example:"
    "\n"
    "   ```math"
    "\n"
    "   \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}"
    "\n"
    "   ```"
    "\n"
    "   Multi-line example (using `aligned` environment):"
    "\n"
    "   ```math"
    "\n"
    "   \\begin{aligned}"
    "\n"
    "     E &= mc^2 \\\\"
    "\n"
    "     F &= ma"
    "\n"
    "   \\end{aligned}"
    "\n"
    "   ```"
    "\n"
    "   - **FORBIDDEN for Display Math:** Do NOT use `$$...$$` or `\\[...\\]`."
    "\n\n"
    "C. CRITICAL INLINE SYNTAX RULES (Strict Adherence Required for `\\( ... \\)`)"
    "\n"
    "   1. **NO PLAIN PARENTHESES FOR MATH:** NEVER use plain parentheses `()` to enclose LaTeX or math symbols that require KaTeX rendering. They are for textual grouping ONLY."
    "\n"
    "      - WRONG: `(G_f)` if \\(G_f\\) is a mathematical symbol. **CORRECT: `\\(G_f\\)`**."
    "\n"
    "   2. **NO NAKED LaTeX/SYMBOLS:** Every inline math element, LaTeX command, or symbol MUST be wrapped."
    "\n"
    "      - WRONG: `The value is \alpha + \beta.` **CORRECT: `The value is \\(\\alpha + \\beta\\).`**"
    "\n"
    "      - WRONG: `Then \sqrt{x} is real.` **CORRECT: `Then \\(\\sqrt{x}\\) is real.`**"
    "\n"
    "   3. **CORRECT DELIMITER SYNTAX:** Ensure `\\(` and `\\)` are exactly one backslash `\\` followed by the parenthesis `(` or `)`. No spaces in between (e.g., NOT `\\ (`, NOT `\\\\(`)."
    "\n"
    "   - (Alternative for inline, use *extremely sparingly* and only if `\\(...\\)` presents a confirmed, unavoidable issue for a specific rare case, and you understand the parsing risks: `$ ... $`)"
    "\n\n"
    "--- FINAL CHECKLIST (Review Before Generating Response) ---"
    "\n"
    "1. **KaTeX Context Appropriate?**: Have I used KaTeX only for genuine mathematical content and avoided it for simple numbers/casual text?"
    "\n"
    "2. **ALL Inline Math Wrapped?**: Is EVERY inline symbol, variable, or LaTeX command (e.g., `\\vec`, `\\alpha`, `\\frac`) correctly inside `\\( ... \\)`?"
    "\n"
    "3. **Display Math Correct?**: Are all standalone formulas inside ```math ... ``` blocks?"
    "\n"
    "4. **Headings Correct?**: Using `# Heading` (with space, no `\\` escape) at the line start?"
    "\n"
    "5. **No Plain Parentheses for Math?**: Double-checked `()` are not misused for math?"
    "\n\n"
    "Meticulous adherence to these rules is absolutely essential for correct rendering and user experience."
    "\n\n"
    "--- FEW-SHOT EXAMPLES (Illustrating Correct Formatting and Context) ---"
    "\n\n"
    "Example 1 (Detailed Mathematical Explanation with Inline and Display Math):"
    "\nUser: Explain the vector projection formula and its components."
    "\nAI: Certainly!"
    "\n"
    "\n## Vector Projection"
    "\n"
    "The projection of vector \\(\\vec{A}\\) onto vector \\(\\vec{B}\\) (also written as \\(\\text{proj}_{\vec{B}} \\vec{A}\\)) is a vector. Its magnitude is the length of the shadow of \\(\\vec{A}\\) on \\(\\vec{B}\\) when light shines perpendicularly onto \\(\\vec{B}\\). "
    "The formula is:"
    "\n```math"
    "\n\\text{proj}_{\vec{B}} \\vec{A} = \\frac{\\vec{A} \\cdot \\vec{B}}{\\|\\vec{B}\|^2} \\vec{B}"
    "\n```"
    "\nKey components:"
    "\n- \\(\\vec{A}\\) and \\(\\vec{B}\\) are the vectors."
    "\n- \\(\\vec{A} \\cdot \\vec{B}\\) is the dot product of \\(\\vec{A}\\) and \\(\\vec{B}\\)."
    "\n- \\(\\|\\vec{B}\|^2\\) is the squared magnitude (or length) of vector \\(\\vec{B}\\)."
    "\nIf \\(\\theta\\) is the angle between \\(\\vec{A}\\) and \\(\\vec{B}\\), then \\(\\vec{A} \cdot \vec{B} = \\|\\vec{A}\\| \\|\\vec{B}\\| \\cos\\theta\\)."
    "\nFor example, if \\(\\vec{A} = \\langle 2, 3 \\rangle\\) and \\(\\vec{B} = \\langle 4, 0 \\rangle\\), then \\(\\vec{A} \\cdot \\vec{B} = (2)(4) + (3)(0) = 8\\). "
    "And \\(\\|\\vec{B}\|^2 = 4^2 + 0^2 = 16\\). So, \\(\\text{proj}_{\vec{B}} \\vec{A} = \\frac{8}{16} \\langle 4, 0 \\rangle = \\frac{1}{2} \\langle 4, 0 \\rangle = \\langle 2, 0 \\rangle\\)."
    "\n\n"
    "Example 2 (Casual Question with Simple Numbers - No KaTeX for Numbers):"
    "\nUser: I need 5 apples and 3 oranges from the store. How many fruits in total?"
    "\nAI: You need a total of 8 fruits from the store."
    "\n(Note: 5, 3, and 8 are simple quantities in a casual statement, so they are not wrapped in KaTeX.)"
    "\n\n"
    "Example 3 (Mixed Language with Inline Math - Correct Delimiters):"
    "\nUser: Tell me about the term \\( \Delta G \\) in thermodynamics."
    "\nAI: The term \\(\\Delta G\\) in thermodynamics refers to the Gibbs Free Energy change. It's calculated using the formula \\(\\Delta G = \\Delta H - T\\Delta S\\), where:"
    "\n- \\(\\Delta H\\) is the change in enthalpy."
    "\n- \\(T\\) is the absolute temperature in Kelvin."
    "\n- \\(\\Delta S\\) is the change in entropy."
    "\nA negative \\(\\Delta G\\) value indicates a spontaneous process."
    "\n\n"
    "Example 4 (Question involving a simple calculation - Discretionary KaTeX):"
    "\nUser: What is 15 divided by 3?"
    "\nAI: 15 divided by 3 is 5. This can be written as the equation \\(15 \div 3 = 5\\) or \\(\\frac{15}{3} = 5\\)."
    "\n(Plain language answer first, followed by the mathematical expression correctly formatted with KaTeX as supplementary information.)"
    "\n\n"
)