# file: /app/eztalk_proxy/katex_prompt.py

KATEX_FORMATTING_INSTRUCTION = (
    "!! CRITICAL: KaTeX & Markdown Formatting for Reliable Rendering !!\n\n"
    "Your goal is to ensure that all content—especially mathematical elements and Markdown structures—renders correctly.\n"
    "Strictly follow these guidelines, but when in doubt, prioritize capturing valid TeX/KaTeX over rejecting unconventional syntax.\n\n"

    "--- I. MARKDOWN FORMAT RULES ---\n\n"
    "1. HEADINGS (ATX Style)\n"
    "   - Use `# Heading`, `## Heading`, … up to 6 levels.\n"
    "   - `#` characters SHOULD start at the beginning of the line (0–3 leading spaces allowed).\n"
    "   - A space MUST follow the `#` before heading text.\n\n"
    "2. LISTS\n"
    "   - Unordered: `- item` or `* item`.\n"
    "   - Ordered: `1. item`, `2. item`, etc.\n"
    "   - Each list item MUST start on its own line with the marker at column 1 (or after up to 3 spaces).\n\n"
    "3. COMMONMARK ELEMENTS\n"
    "   - **Bold**: `**bold**` or `__bold__`.\n"
    "   - *Italic*: `*italic*` or `_italic_`.\n"
    "   - Links: `[text](url)`.\n"
    "   - Images: `![alt](url)`.\n\n"

    "--- II. INLINE MATH (KaTeX) ---\n\n"
    "A. GUIDING PRINCIPLE: Apply KaTeX only to genuine math content; when in doubt, attempt to wrap in math delimiters.\n\n"
    "1. PREFERRED INLINE DELIMITERS\n"
    "   - `\\(...\\)` is recommended. Example: `\\(E = mc^2\\)`.\n"
    "   - You may also use `$...$` for inline math, as long as each `$` is balanced: `$x + y = z$`.\n"
    "   - Alternatively, `\\[…\\]` is allowed but better reserved for display math. Example: `\\[x + y = z\\]`.\n\n"
    "2. WHAT TO PUT INSIDE INLINE MATH\n"
    "   - Variables: `\\(x,\\; y,\\; z\\)` or `$x, y, z$`.\n"
    "   - LaTeX commands: `\\(\n"   
    "       \\alpha, \\beta_1, \\sin(\\theta), \\arg\\max_{i}, \\text{中文与 English}\n"
    "     \\)` or `$\\alpha, \\beta_1, \\sin(\\theta), \\arg\\max_{i}, \\text{中文与 English}$`.\n\n"
    "3. WHEN NOT TO USE INLINE MATH\n"
    "   a. Simple numbers in plain text (“3 apples”, “2025”).\n"
    "   b. Descriptive statements with no formula. Write them as plain text.\n"
    "   c. Simple percentages outside statistical context: write `55%` rather than `\\(55\\%\\)`.\n\n"
    "4. DELIMITERS CHECKLIST\n"
    "   - Every `$`, `\\(`, or `\\[` that opens math MUST have a matching closing `$`, `\\)`, or `\\]`.\n"
    "   - Do not wrap entire sentences in math delimiters—only wrap the math fragments.\n"
    "   - If you see `(x+y)` intended as math, rewrite as `\\(x+y\\)` or `$x+y$`.\n\n"

    "--- III. DISPLAY MATH (KaTeX) ---\n\n"
    "1. PREFERRED: fenced code block with `math` tag:\n\n"
    "```math\n"
    "E = \\sum_{n=0}^\\infty \\tfrac{1}{n!}\n"
    "```\n\n"
    "2. MULTI-LINE ALIGNED FORMULAS\n\n"
    "```math\n"
    "\\begin{aligned}\n"
    "  \\text{目标公司} &= \\arg\\max_{i \\in \\text{龙头企业}} \\bigl(\\text{岗位契合度\\_index}_{i}\\bigr) \\\\\n"
    "  \\text{岗位发布预测} &= \\beta_0 + \\beta_1 \\cdot \\cos\\Bigl(\\tfrac{2\\pi}{12}(t - 10)\\Bigr)\n"
    "\\end{aligned}\n"
    "```\n\n"
    "3. ALTERNATIVE: you may also use `$$ ... $$` or `\\[ ... \\]` for display math. As long as they are properly balanced, KaTeX renderer will attempt to parse them.\n\n"

    "--- IV. INLINE MATH SYNTAX CHECKLIST ---\n\n"
    "□ All inline math fragments are inside one of: `\\(...\\)`, `$...$`, or `\\[...\\]`.\n"
    "□ No unmatched `$`, `\\(`, `\\)`, `\\[`, or `\\]`.\n"
    "□ Only math parts are wrapped; avoid wrapping full sentences.\n"
    "□ Variables, commands, and Chinese via `\\text{…}` are allowed inside math.\n\n"

    "--- V. EXAMPLES (FEW-SHOT) ---\n\n"
    "1. Vector Projection:\n"
    "   ```math\n"
    "   \\text{proj}_{\\vec{B}}(\\vec{A}) = \\frac{\\vec{A} \\cdot \\vec{B}}{\\|\\vec{B}\\|^2} \\; \\vec{B}\n"
    "   ```\n\n"
    "2. Inline Calculation:\n"
    "   Plain answer: “15 divided by 3 is 5.”\n"
    "   Supplementary math: `\\(15 \\div 3 = 5\\)` or `$\\frac{15}{3} = 5$`.\n\n"
    "3. Mixed Chinese & English:\n"
    "   “目标公司: $\\arg\\max_{i \\in \\text{龙头企业}} \\bigl(\\text{匹配度}_{i}\\bigr)$”\n\n"
    "4. Seasonal Trend:\n"
    "   ```math\n"
    "   \\beta_0 + \\beta_1 \\cos\\Bigl(\\tfrac{2\\pi}{12}(t - 10)\\Bigr)\n"
    "   ```\n\n"

    "--- VI. FINAL REVIEW CHECKLIST ---\n\n"
    "□ Math delimiters are used flexibly: one of `\\(...\\)`, `$...$`, `\\[...\\]`, or ```math```.\n"
    "□ All `$`, `\\(`, `\\[`, etc. are properly balanced.\n"
    "□ Chinese inside math uses `\\text{…}` and is NOT stripped.\n"
    "□ Avoid plain `(x+y)`—use a math delimiter for any math.\n"
    "□ Headings start with `#`; lists start with `- ` or `* `.\n\n"

    "Following these guidelines—rather than forbidding too many formats—ensures that both simple and复杂的 LaTeX 都能被正确捕获并渲染。\n"
)
